### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-dojo#37]
Set up docs on readthedocs. 4 main sections:

- Tutorial (walk through of using the library with 1 archetype and 1 algorithm)
- How to's for each "thing"
- Reference: bibliography, theoretic discussions of algorithms and archetypes. 
- Discussion: more background discussion about the ideas etc... To include things like @marcharper said on #36:
   > The particle swarm algorithm is better suited for Gambler and HMM that have continuous parameters (and are "stochastic"). For FSM and Lookerup the evolutionary algorithm makes more sense IMO since one has better control over how the mutation proceeds and the parameters are categorical (typically producing deterministic strategies). The existing HMM script used the evolutionary algorithm out of laziness and I suspected that the PSO algorithm would be more efficient

(These 4 sections is based on https://www.divio.com/en/blog/documentation/, it's more or less what we're now doing with Axelrod and what I've verbosely done for Nashpy :))

I'm happy to pick this up as an ongoing project :+1:

**Comment by evildmp** [comment]
I'm preparing a clone-it-and-go repository for the documentation structure, that also documents itself. It includes things like a Makefile with spelling checks, a local documentation server, etc. Will be ready soon.

**Comment by drvinceknight** [comment]
Nice initiative! I expect we'll be fine just using a vanilla setup but will take a look :) :+1:
