### ISSUE TITLE
Fix "Swap Two Nodes" in FSM mutate_rows method

### ISSUE THREAD

**Issue by gaffney2010** [Axelrod-Python/axelrod-dojo#41]
I'm looking at the mutate_rows method of fsm.py:

    @staticmethod
    def mutate_rows(rows, mutation_probability):
        randoms = np.random.random(len(rows))
        # Flip each value with a probability proportional to the mutation rate
        for i, row in enumerate(rows):
            if randoms[i] < mutation_probability:
                row[3] = row[3].flip()
        # Swap Two Nodes?
        if random.random() < 0.5:
            nodes = len(rows) // 2
            n1 = randrange(nodes)
            n2 = randrange(nodes)
            for j, row in enumerate(rows):
                if row[1] == n1:
                    row[1] = n2
                elif row[1] == n2:
                    row[1] = n1
        return rows

I think that n1 and n2 are set to numbers, but row[1] will be a C or a D, so that the two if statements are never getting run.

I tested this by raising exceptions in both the if statements and running the attached test (which is just part of the test_fsm.py file with mutation_probability turned up to 100% and run for 100 generations).  We should expect that the Swap Two Nodes logic gets run about half the time, but the exception never gets raised.
[mytest.txt](https://github.com/Axelrod-Python/axelrod-dojo/files/1538368/mytest.txt)

The tempting way to fix this is to change "row[1]" to "row[0]", but that'll raise more issues, because the cross-over logic assumes that the states will be in order.  [You can run my attached code again and get an error.]  You can reorder the states in the mutate_rows method, but there's a way to modify the crossover_rows code so that you don't need this ordered, then it'll be faster.

Let me know if I should give anything more.  Sorry if I've misunderstood anything.

**Comment by marcharper** [comment]
Good catch. If we correct row[1] to row[0] can we simply sort to ensure that crossover continues to work? Otherwise I recommend we just remove this code block, since the code works well despite it never being called.

Also, it would be great to have more test coverage in this repository -- it's less mature than the Axelrod repository and still needs many tests.

**Comment by gaffney2010** [comment]
You _could_ simply sort.  But I'm wondering too, if we keep the order to make the crossover work, then why is the crossover an _ordered_ crossover anyway?  I think the order of these states isn't meaningful, so couldn't we (shouldn't we) pick just _some_ states from each parent, rather than the first m from one and the last n from another?  [I think we can do that in linear time and let the states become unordered.]

**Comment by marcharper** [comment]
It doesn't really matter I think, particularly since we were able to evolve excellent strategies with the existing broken code. The crossover as implemented is by analogy with the biological process. Perhaps we should simply fix the swapping and leave the crossover alone pending some test runs.

**Comment by gaffney2010** [comment]
I agree that it won't make much difference.  So if you think it's better to leave the crossover alone, that's fine with me.  Let me know if I should change the code to fix the swap and to sort.

**Comment by drvinceknight** [comment]
Thanks for raising the issue @gaffney2010 :+1:

> Perhaps we should simply fix the swapping and leave the crossover alone pending some test runs.

I'd be in favour of this :)

@gaffney2010 do you want to take this?

**Comment by gaffney2010** [comment]
> do you want to take this?

Sure.

**Comment by drvinceknight** [comment]
Closed by #42
