### ISSUE TITLE
Multithreadding on windows dosent work.

### ISSUE THREAD

**Issue by GitToby** [Axelrod-Python/axelrod-dojo#46]
When running a GA on a windows box there are issues with the starmap methods not working on windows.

**Comment by GitToby** [comment]
axelrod_dojo/algorithms/genetic_algorithm.py:67

**Comment by drvinceknight** [comment]
For this to be helpful could you put some of the stack trace here.

**Comment by GitToby** [comment]
This seems to have been fixed for the windows issue.

**Comment by drvinceknight** [comment]
Ok, thanks I'll close this.
